# dev 環境
[DEV]
WORKER_ACCOUNT = worker
WORKER_PASSWORD = worker
RABBITMQ_HOST = 127.0.0.1
RABBITMQ_PORT = 5672
MYSQL_HOST = 127.0.0.1
MYSQL_PORT = 3306
MYSQL_ACCOUNT = root
MYSQL_PASSWORD = ppWgnb_mfGe2m_

# Docker 環境
[DOCKER]
WORKER_ACCOUNT = worker
WORKER_PASSWORD = worker
RABBITMQ_HOST = rabbitmq
RABBITMQ_PORT = 5672
MYSQL_HOST = mysql
MYSQL_PORT = 3306
MYSQL_ACCOUNT = root
MYSQL_PASSWORD = ppWgnb_mfGe2m_

# Prod 環境
[PRODUCTION]
WORKER_ACCOUNT = worker
WORKER_PASSWORD = worker
RABBITMQ_HOST = 實體 IP
RABBITMQ_PORT = 5672
MYSQL_HOST = 實體 IP
MYSQL_PORT = 3306
MYSQL_ACCOUNT = root
MYSQL_PASSWORD = ppWgnb_mfGe2m_
